//export const serverURL = "http://localhost:8090"
export const serverURL = "http://142.93.15.140:8090"

export const MusicGenres = [
  {value: 'Pop', label: 'Pop'},
  {value: 'Rock', label: 'Rock'},
  {value: 'Hip-hop', label: 'Hip-hop'},
  {value: 'R&B (Ritmo y Blues)', label: 'R&B (Ritmo y Blues)'},
  {value: 'Country', label: 'Country'},
  {value: 'Jazz', label: 'Jazz'},
  {value: 'Blues', label: 'Blues'},
  {value: 'Electrónica', label: 'Electrónica'},
  {value: 'Dance', label: 'Dance'},
  {value: 'Reggae', label: 'Reggae'},
  {value: 'Gospel', label: 'Gospel'},
  {value: 'Alternativo', label: 'Alternativo'},
  {value: 'Indie', label: 'Indie'},
  {value: 'Folk', label: 'Folk'},
  {value: 'Punk', label: 'Punk'},
  {value: 'Metal', label: 'Metal'},
  {value: 'Clásica', label: 'Clásica'},
  {value: 'Soul', label: 'Soul'},
  {value: 'Funk', label: 'Funk'},
  {value: 'Disco', label: 'Disco'},
  {value: 'Ska', label: 'Ska'},
  {value: 'Rap', label: 'Rap'},
  {value: 'Grunge', label: 'Grunge'},
  {value: 'New Wave', label: 'New Wave'},
  {value: 'Techno', label: 'Techno'},
  {value: 'House', label: 'House'},
  {value: 'Dubstep', label: 'Dubstep'},
  {value: 'Latina', label: 'Latina'},
  {value: 'Reguetón', label: 'Reguetón'},
  {value: 'Salsa', label: 'Salsa'},
  {value: 'Mariachi', label: 'Mariachi'},
  {value: 'Norteño', label: 'Norteño'},
  {value: 'Ranchera', label: 'Ranchera'},
  {value: 'Cumbia', label: 'Cumbia'},
  {value: 'Vallenato', label: 'Vallenato'},
  {value: 'Porro', label: 'Porro'},
  {value: 'Carranga', label: 'Carranga'},
  {value: 'Corridos', label: 'Corridos'}
];

